mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user: root
  password: 123456
  log_level: dev

#系统基础配置
system:
  host: "0.0.0.0"
  port: 8080
  env: dev

#日志怕配置
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true